definitions:
  response.EchoR:
    properties:
      code:
        type: integer
      data: {}
      msg:
        type: string
    type: object
info:
  contact: {}
paths:
  /ip:
    get:
      consumes:
      - application/json
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.EchoR'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.EchoR'
      summary: Get ip data
      tags:
      - IP
  /s3:
    post:
      consumes:
      - multipart/form-data
      description: Upload file
      parameters:
      - description: this is a test file
        in: formData
        name: file
        required: true
        type: file
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/response.EchoR'
        "400":
          description: Bad Request
          schema:
            $ref: '#/definitions/response.EchoR'
      summary: Post upload file
      tags:
      - S3
swagger: "2.0"
